export interface JournalEntry {
  title: string;
  date: string;
  content: string;
  isRestDay: boolean;
  metrics: {
    miles: number;
    elevation: number;
  };
  weather?: {
    max: number;
    min: number;
    precip: number;
    code: number;
  };
}

export const journalEntries: Record<string, JournalEntry> = {
  "1": {
    title: "Georgetown, TX",
    date: "May-17",
    content:
      "Today was the day we left from Austin! A hard first day to be sure, with a crash right out of the gate, but with an awesome rest stop from Noah's family and Round Rock donuts we finished on a more positive note.",
    isRestDay: false,
    metrics: { miles: 37.7, elevation: 1501 },
  },
  "2": {
    title: "Waco, TX",
    date: "May-18",
    content: "",
    isRestDay: false,
    metrics: { miles: 84.9, elevation: 2582 },
  },
  "3": {
    title: "Waxahachie, TX",
    date: "May-19",
    content: "",
    isRestDay: false,
    metrics: { miles: 75.5, elevation: 2148 },
  },
  "4": {
    title: "Dallas, TX",
    date: "May-20",
    content: "",
    isRestDay: false,
    metrics: { miles: 57.7, elevation: 1695 },
  },
  "5": {
    title: "Dallas, TX",
    date: "May-21",
    content: "Rest Day in Dallas.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "6": {
    title: "Gainesville, TX",
    date: "May-22",
    content: "",
    isRestDay: false,
    metrics: { miles: 55.1, elevation: 1349 },
  },
  "7": {
    title: "Wynnewood, OK",
    date: "May-23",
    content: "",
    isRestDay: false,
    metrics: { miles: 108.1, elevation: 4678 },
  },
  "8": {
    title: "Oklahoma City, OK",
    date: "May-24",
    content: "",
    isRestDay: false,
    metrics: { miles: 95.5, elevation: 4830 },
  },
  "9": {
    title: "Oklahoma City, OK",
    date: "May-25",
    content: "Rest Day in OKC.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "10": {
    title: "Watonga, OK",
    date: "May-26",
    content: "",
    isRestDay: false,
    metrics: { miles: 83.0, elevation: 2100 },
  },
  "11": {
    title: "Woodward, OK",
    date: "May-27",
    content: "",
    isRestDay: false,
    metrics: { miles: 72.4, elevation: 2671 },
  },
  "12": {
    title: "Guymon, OK",
    date: "May-28",
    content: "",
    isRestDay: false,
    metrics: { miles: 85.0, elevation: 3170 },
  },
  "13": {
    title: "Clayton, NM",
    date: "May-29",
    content: "",
    isRestDay: false,
    metrics: { miles: 107.9, elevation: 2662 },
  },
  "14": {
    title: "Trinidad, CO",
    date: "May-30",
    content: "",
    isRestDay: false,
    metrics: { miles: 95.2, elevation: 4472 },
  },
  "15": {
    title: "Pueblo, CO",
    date: "May-31",
    content: "",
    isRestDay: false,
    metrics: { miles: 93.5, elevation: 3057 },
  },
  "16": {
    title: "Colorado Springs, CO",
    date: "Jun-1",
    content: "",
    isRestDay: false,
    metrics: { miles: 56.0, elevation: 2220 },
  },
  "17": {
    title: "Denver, CO",
    date: "Jun-2",
    content: "",
    isRestDay: false,
    metrics: { miles: 80.0, elevation: 4200 },
  },
  "18": {
    title: "Denver, CO",
    date: "Jun-3",
    content: "Rest Day in Denver.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "19": {
    title: "Estes Park / Rocky Mountain NP, CO",
    date: "Jun-4",
    content: "",
    isRestDay: false,
    metrics: { miles: 86.0, elevation: 5511 },
  },
  "20": {
    title: "Steamboat Springs, CO",
    date: "Jun-5",
    content: "",
    isRestDay: false,
    metrics: { miles: 85.2, elevation: 4505 },
  },
  "21": {
    title: "Dinosaur NM, UT",
    date: "Jun-6",
    content: "",
    isRestDay: false,
    metrics: { miles: 100.0, elevation: 3959 },
  },
  "22": {
    title: "Fruitland, UT",
    date: "Jun-7",
    content: "",
    isRestDay: false,
    metrics: { miles: 104.7, elevation: 5682 },
  },
  "23": {
    title: "Salt Lake City, UT",
    date: "Jun-8",
    content: "",
    isRestDay: false,
    metrics: { miles: 120.8, elevation: 4822 },
  },
  "24": {
    title: "Salt Lake City, UT",
    date: "Jun-9",
    content: "Rest Day in SLC.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "25": {
    title: "Logan, UT",
    date: "Jun-10",
    content: "",
    isRestDay: false,
    metrics: { miles: 80.7, elevation: 2862 },
  },
  "26": {
    title: "Pocatello, ID",
    date: "Jun-11",
    content: "",
    isRestDay: false,
    metrics: { miles: 101.6, elevation: 2485 },
  },
  "27": {
    title: "Idaho Falls, ID",
    date: "Jun-12",
    content: "",
    isRestDay: false,
    metrics: { miles: 48.1, elevation: 485 },
  },
  "28": {
    title: "Grand Teton NP, WY",
    date: "Jun-13",
    content: "",
    isRestDay: false,
    metrics: { miles: 119.0, elevation: 5518 },
  },
  "29": {
    title: "Grand Teton NP, WY",
    date: "Jun-14",
    content: "Rest Day in the Tetons.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "30": {
    title: "Yellowstone NP, WY",
    date: "Jun-15",
    content: "",
    isRestDay: false,
    metrics: { miles: 55.0, elevation: 2532 },
  },
  "31": {
    title: "Big Sky, MT",
    date: "Jun-16",
    content: "",
    isRestDay: false,
    metrics: { miles: 37.2, elevation: 1160 },
  },
  "32": {
    title: "Bozeman, MT",
    date: "Jun-17",
    content: "",
    isRestDay: false,
    metrics: { miles: 75.0, elevation: 3224 },
  },
  "33": {
    title: "Helena, MT",
    date: "Jun-18",
    content: "",
    isRestDay: false,
    metrics: { miles: 122.1, elevation: 2513 },
  },
  "34": {
    title: "Missoula, MT",
    date: "Jun-19",
    content: "",
    isRestDay: false,
    metrics: { miles: 135.6, elevation: 5352 },
  },
  "35": {
    title: "Kalispell, MT",
    date: "Jun-20",
    content: "",
    isRestDay: false,
    metrics: { miles: 119.2, elevation: 4454 },
  },
  "36": {
    title: "Glacier NP, MT",
    date: "Jun-21",
    content: "",
    isRestDay: false,
    metrics: { miles: 34.3, elevation: 1209 },
  },
  "37": {
    title: "Glacier NP, MT",
    date: "Jun-22",
    content: "Rest Day in Glacier.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "38": {
    title: "Claresholm, AB",
    date: "Jun-23",
    content: "Welcome to Canada!",
    isRestDay: false,
    metrics: { miles: 88.8, elevation: 1734 },
  },
  "39": {
    title: "Calgary, AB",
    date: "Jun-24",
    content: "",
    isRestDay: false,
    metrics: { miles: 95.8, elevation: 2617 },
  },
  "40": {
    title: "Banff, AB [Canmore]",
    date: "Jun-25",
    content: "",
    isRestDay: false,
    metrics: { miles: 88.3, elevation: 4411 },
  },
  "41": {
    title: "Banff NP, AB",
    date: "Jun-26",
    content: "",
    isRestDay: false,
    metrics: { miles: 28.3, elevation: 1784 },
  },
  "42": {
    title: "Jasper, AB",
    date: "Jun-27",
    content: "The Icefields Parkway.",
    isRestDay: false,
    metrics: { miles: 164.8, elevation: 9033 },
  },
  "43": {
    title: "Jasper, AB",
    date: "Jun-28",
    content: "Rest Day in Jasper.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "44": {
    title: "McBride, BC",
    date: "Jun-29",
    content: "",
    isRestDay: false,
    metrics: { miles: 114.6, elevation: 5033 },
  },
  "45": {
    title: "Purden Lake, BC",
    date: "Jun-30",
    content: "",
    isRestDay: false,
    metrics: { miles: 95.0, elevation: 5583 },
  },
  "46": {
    title: "Prince George, BC",
    date: "Jul-1",
    content: "Canada Day!",
    isRestDay: false,
    metrics: { miles: 43.8, elevation: 2285 },
  },
  "47": {
    title: "Vanderhoof, BC",
    date: "Jul-2",
    content: "",
    isRestDay: false,
    metrics: { miles: 56.5, elevation: 2444 },
  },
  "48": {
    title: "Burns Lake, BC",
    date: "Jul-3",
    content: "",
    isRestDay: false,
    metrics: { miles: 80.6, elevation: 3530 },
  },
  "49": {
    title: "Burns Lake, BC",
    date: "Jul-4",
    content: "Rest Day.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "50": {
    title: "Smithers, BC",
    date: "Jul-5",
    content: "",
    isRestDay: false,
    metrics: { miles: 90.1, elevation: 3900 },
  },
  "51": {
    title: "Kitwanga, BC",
    date: "Jul-6",
    content: "",
    isRestDay: false,
    metrics: { miles: 72.4, elevation: 3466 },
  },
  "52": {
    title: "Meziadin Junction, BC",
    date: "Jul-7",
    content: "",
    isRestDay: false,
    metrics: { miles: 94.8, elevation: 4308 },
  },
  "53": {
    title: "Kinaskan Lake Provincial Park",
    date: "Jul-8",
    content: "",
    isRestDay: false,
    metrics: { miles: 130.5, elevation: 9435 },
  },
  "54": {
    title: "Morchuea Lake Camping",
    date: "Jul-9",
    content: "",
    isRestDay: false,
    metrics: { miles: 37.3, elevation: 2184 },
  },
  "55": {
    title: "Dease Lake, BC",
    date: "Jul-10",
    content: "",
    isRestDay: false,
    metrics: { miles: 54.9, elevation: 3136 },
  },
  "56": {
    title: "Dease Lake, BC",
    date: "Jul-11",
    content: "Rest Day.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "57": {
    title: "Jade City, BC",
    date: "Jul-12",
    content: "",
    isRestDay: false,
    metrics: { miles: 86.4, elevation: 5178 },
  },
  "58": {
    title: "Rancheria, YT",
    date: "Jul-13",
    content: "Welcome to the Yukon!",
    isRestDay: false,
    metrics: { miles: 100.3, elevation: 5369 },
  },
  "59": {
    title: "Teslin, YT",
    date: "Jul-14",
    content: "",
    isRestDay: false,
    metrics: { miles: 123.4, elevation: 7584 },
  },
  "60": {
    title: "Whitehorse, YT",
    date: "Jul-15",
    content: "",
    isRestDay: false,
    metrics: { miles: 100.8, elevation: 6028 },
  },
  "61": {
    title: "Whitehorse, YT",
    date: "Jul-16",
    content: "Rest Day.",
    isRestDay: true,
    metrics: { miles: 0, elevation: 0 },
  },
  "62": {
    title: "Haines Junction, YT",
    date: "Jul-17",
    content: "",
    isRestDay: false,
    metrics: { miles: 96.0, elevation: 4720 },
  },
  "63": {
    title: "Burwash Landing, YT",
    date: "Jul-18",
    content: "",
    isRestDay: false,
    metrics: { miles: 55.0, elevation: 4820 },
  },
  "64": {
    title: "Beaver Creek, YT",
    date: "Jul-19",
    content: "",
    isRestDay: false,
    metrics: { miles: 105.0, elevation: 5270 },
  },
  "65": {
    title: "Tok, AK",
    date: "Jul-20",
    content: "Welcome to Alaska!",
    isRestDay: false,
    metrics: { miles: 109.0, elevation: 7930 },
  },
  "66": {
    title: "Chistochina, AK",
    date: "Jul-21",
    content: "",
    isRestDay: false,
    metrics: { miles: 90.0, elevation: 9990 },
  },
  "67": {
    title: "Glennallen, AK",
    date: "Jul-22",
    content: "",
    isRestDay: false,
    metrics: { miles: 48.0, elevation: 3350 },
  },
  "68": {
    title: "Nelchina, AK",
    date: "Jul-23",
    content: "",
    isRestDay: false,
    metrics: { miles: 77.0, elevation: 6500 },
  },
  "69": {
    title: "Wasilla, AK",
    date: "Jul-24",
    content: "",
    isRestDay: false,
    metrics: { miles: 35.0, elevation: 2380 },
  },
  "70": {
    title: "Anchorage, AK",
    date: "Jul-25",
    content: "WE MADE IT!",
    isRestDay: false,
    metrics: { miles: 45.0, elevation: 5000 },
  },
};
